# Generated by Django 4.1.10 on 2023-09-29 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='ایمیل')),
                ('phone', models.CharField(max_length=11, unique=True, verbose_name='شماره تلفن')),
                ('f_name', models.CharField(max_length=200, null=True, verbose_name='نام')),
                ('l_name', models.CharField(max_length=200, null=True, verbose_name='نام خانوادگی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_admin', models.BooleanField(default=False, verbose_name='ادمین')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربر ها',
                'ordering': ['email'],
            },
        ),
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, verbose_name='ایمیل')),
                ('phone', models.IntegerField(verbose_name='شماره تلفن')),
                ('f_name', models.CharField(max_length=200, null=True, verbose_name='نام')),
                ('l_name', models.CharField(max_length=200, null=True, verbose_name='نام خانوادگی')),
                ('password', models.CharField(max_length=16, verbose_name='رمز عبور')),
                ('password_conf', models.CharField(max_length=16, verbose_name='رمز تایید شده')),
                ('otp_code', models.IntegerField(verbose_name='کد اعتبار سنجی')),
                ('expiration', models.DateTimeField(auto_now_add=True, verbose_name='زمان اعتبار سنجی')),
                ('token', models.CharField(max_length=100, unique=True, verbose_name='توکن')),
            ],
            options={
                'ordering': ['email'],
            },
        ),
        migrations.CreateModel(
            name='UserAddres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=200, verbose_name='شماره تلقن')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('f_name', models.CharField(max_length=200, verbose_name='نلم')),
                ('l_name', models.CharField(max_length=200, verbose_name='نام خانوادگی')),
                ('city', models.CharField(max_length=200, verbose_name='شهر')),
                ('plak', models.CharField(max_length=200, verbose_name='پلاک')),
                ('postal_code', models.CharField(max_length=200, verbose_name='کد پستی')),
                ('addres', models.CharField(max_length=300, verbose_name='آدرس')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_addres', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'آدرس کاربر ها',
                'verbose_name_plural': 'آدرس های کاربر ها',
            },
        ),
    ]
