# Generated by Django 4.1.10 on 2023-09-28 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='phone',
            field=models.IntegerField(max_length=11, unique=True, verbose_name='شماره تلفن'),
        ),
    ]
