# Generated by Django 4.1.10 on 2023-09-28 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_otp_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='phone',
            field=models.IntegerField(max_length=11, verbose_name='شماره تلفن'),
        ),
    ]
