# Generated by Django 4.1.10 on 2023-09-16 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11, verbose_name='شماره تلفن')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('adress', models.CharField(max_length=200, verbose_name='آدرس')),
                ('instagram_id', models.CharField(max_length=200, verbose_name='آیدی اینستا')),
                ('instagram_url', models.URLField(null=True, verbose_name='لینک بیج اینستا')),
            ],
            options={
                'verbose_name': 'تماس با ما',
                'verbose_name_plural': 'تماس ها',
            },
        ),
        migrations.CreateModel(
            name='UserContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام کاربر')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل کاربر')),
                ('phone', models.CharField(max_length=11, verbose_name='شماره تماس کاربر')),
                ('title', models.CharField(max_length=200, verbose_name='موضوع')),
                ('text', models.TextField(verbose_name='متن')),
            ],
            options={
                'verbose_name': 'تماس کاربر',
                'verbose_name_plural': 'تماس های کاربر',
            },
        ),
    ]
