# Generated by Django 4.1.10 on 2023-09-21 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='عنوان دسته بندی')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='اسلاگ دسته بندی')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=200, unique=True, verbose_name='رنگ')),
            ],
            options={
                'verbose_name': 'رنگ',
                'verbose_name_plural': 'رنگ ها',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=200, unique=True, verbose_name='سایز')),
            ],
            options={
                'verbose_name': 'سایز',
                'verbose_name_plural': 'سایز ها',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام محصول')),
                ('slug', models.SlugField(max_length=200, verbose_name='اسلاگ محصول')),
                ('image_1', models.ImageField(null=True, upload_to='products/%Y/%m/%d', verbose_name='تصویر اصلی محصول')),
                ('image_2', models.ImageField(null=True, upload_to='products/%Y/%m/%d', verbose_name='تصویر دوم محصول')),
                ('image_3', models.ImageField(null=True, upload_to='products/%Y/%m/%d', verbose_name='تصویر اصلی محصول')),
                ('image_4', models.ImageField(null=True, upload_to='products/%Y/%m/%d', verbose_name='تصویر اصلی محصول')),
                ('description', models.TextField(null=True, verbose_name='توضیحات محصول')),
                ('price', models.IntegerField(verbose_name='قیمت محصول')),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='تعداد محصول')),
                ('available', models.BooleanField(default=True, verbose_name='موجوده؟')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category', verbose_name='دسته بندی محصول')),
                ('colors', models.ManyToManyField(to='products.color', verbose_name='رنگ های موجود محصول')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.size', verbose_name='سایز محصول')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['name'], name='products_ca_name_693421_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['id', 'slug'], name='products_pr_id_a08e3c_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='products_pr_name_9ff0a3_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-created'], name='products_pr_created_1360ea_idx'),
        ),
    ]
