# Generated by Django 4.1.10 on 2023-10-04 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['updated'], 'verbose_name': 'محصول', 'verbose_name_plural': 'محصولات'},
        ),
    ]
