# Generated by Django 4.1.10 on 2023-09-24 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_comment_product_alter_comment_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='products.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'توضیح',
                'verbose_name_plural': 'توضیحات',
            },
        ),
    ]
