# Generated by Django 4.1.10 on 2023-09-24 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productdescription'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productdescription',
            options={'verbose_name': 'توضیحات محصول', 'verbose_name_plural': 'توضیحات محصولات'},
        ),
        migrations.AlterField(
            model_name='productdescription',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_descriptions', to='products.product', verbose_name='محصول'),
        ),
    ]
